### ISSUE TITLE
Takes longer time to generate the functions project in a folder

### ISSUE THREAD

**Issue by kamini-kamal** [Azure/azure-functions-on-container-apps#10]
On running the command `func init LocalFunctionProj --worker-runtime dotnet-isolated --docker --target-framework net7.0`

- The user is not informed about the status of the process whether it's in progress or waiting (something like a progressbar) even though the folder is generated (task completes).
- What can be done to avoid the errors shown in the image below?
<img width="859" alt="image" src="https://user-images.githubusercontent.com/103620498/235484429-76e9abc8-6cd2-401d-9599-251526588129.png">

**Comment by raorugan** [comment]
This is fixed. The error while executing dotnet isolated should be fixed now.
