### ISSUE TITLE
How is .NET version picked up in the Dockerfile when FUNCTIONS_WORKER_RUNTIME is set to "dotnet"?

### ISSUE THREAD

**Issue by kamini-kamal** [Azure/azure-functions-on-container-apps#11]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/103620498/235486462-1f69f50b-801d-4ba4-b750-f2a047e4f744.png">
The Dockerfile has  dotnet sdk version set to 6.0 when the value of `--worker-runtime` is `dotnet`
<img width="833" alt="image" src="https://user-images.githubusercontent.com/103620498/235486662-09945adb-e3f0-4857-9e2e-092c57a633f4.png">

How is the version selection done in this case?

**Comment by jainharsh98** [comment]
@kamini-kamal dotnet in-proc does not support .net7 - Check supported versions [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v4%2Ccmd#supported-versions). Please try dotnet-isolated worker runtime for .net7 support. // @raorugan
