### ISSUE TITLE
Debug logs present in App Insights 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-on-container-apps#21]
I have a Function app that has Durable Functions and two HTTP triggers, one is a "vanilla" HTTP trigger and the other is to start a Durable Functions Orchestration. I deployed the app to Azure. It appears that debug logs are shipped to the App Insights instance that's created with the Function app, which is going to create a really bad user experience and customer bill. 

Example of debug logs for Durable Functions, which appear even when the Durable Functions Orchestration isn't started: 
<img width="661" alt="image" src="https://github.com/Azure/azure-functions-on-container-apps/assets/25314976/11f19c60-fd4a-4263-a516-e3e206d00f09">

I have another Function app that has an HTTP and EventHubs trigger, and I'm seeing something similar. So it seems like it's **not** specific to Durable Functions:

Example of debug logs for HTTP trigger:
<img width="428" alt="MicrosoftTeams-image (2)" src="https://github.com/Azure/azure-functions-on-container-apps/assets/25314976/7efd7f9b-44f5-4446-86aa-ec704f29d36a">

Repro:
1. Follow REAME instructions to deploy app to Azure
2. Go to the application insights instance associated with the Function app
3. Click to the "live metrics" tab on the left menu, then look at the top right for "sample telemetry". Expanding some traces show that they're debug logs.

**Comment by krishnajaju** [comment]
Hi @lilyjma, thanks for reaching out. I believe this is an expected default behavior of functions host, as I see the same default behavior when deploying a Function App in Elastic Premium SKU with HTTP trigger. 
![image](https://github.com/Azure/azure-functions-on-container-apps/assets/19823543/8d0c76a0-4a53-4b05-adaa-89c49cf23ce3)
Can you please try to configure and customize the data that your Function App sends to Application Insights by following this documentation - https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2? There are ways to configure categories/levels of logs pushed, configure sampling, aggregation, etc.
