### ISSUE TITLE
Applications Insights not Enabled when deploying with Azure CLI

### ISSUE THREAD

**Issue by KaiWalter** [Azure/azure-functions-on-container-apps#22]
When I deploy some Functions on ACA with CLI like

```shell
        az functionapp create -g $RESOURCE_GROUP_NAME --name $app \
        --environment $ENVIRONMENT_NAME \
        --functions-version 4 \
        --runtime dotnet-isolated \
        --storage-account $STORAGE_NAME \
        --app-insights $APPINSIGHTS_NAME \
        --app-insights-key $APPINSIGHTS_INSTRUMENTATIONKEY \
        --image $AZURE_CONTAINER_REGISTRY_ENDPOINT/$IMAGE
```

and initialize Application Insights in `Program.cs` like

```csharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(builder =>
    {
        builder
            .AddApplicationInsights()
            .AddApplicationInsightsLogger();
    })
    .Build();

await host.RunAsync();
```

I cannot see telemetry in Application Insights and noticed, that Application Insights is not enabled on the Functions Resource

![image](https://github.com/Azure/azure-functions-on-container-apps/assets/7418323/8f7cb416-ca47-4ca6-ac0a-9c4573e0f196)

```shell
$ azure-cli                         2.48.1 *

core                              2.48.1 *
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.137
containerapp                      0.3.29

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/kai/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Apr 25 2023, 04:23:10) [GCC 11.3.0]
```

**Comment by raorugan** [comment]
Have you seen any deployment errors while creating this function app? Btw we have launched Azure Functions on ACA in public preview - https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-functions-for-cloud-native-microservices-public-preview/ba-p/3826800. You may now try Bicep deployments as well

**Comment by raorugan** [comment]
Can you share the az functionapp create --debug output?

**Comment by raorugan** [comment]
@KaiWalter  - please confirm if this issue is resolved?

**Comment by KaiWalter** [comment]
@raorugan sorry, deleted the Functions on ACA apps and re-created 'em - see #7 

but still Application Insights does not seem to be enabled
![image](https://github.com/Azure/azure-functions-on-container-apps/assets/7418323/d7e334d7-e567-4880-a003-569a10318ba5)

with my CLI version of a create:

```shell
    az functionapp create -g $RESOURCE_GROUP_NAME --name $capp \
      --environment $ENVIRONMENT_NAME \
      --functions-version 4 \
      --runtime dotnet-isolated \
      --storage-account $STORAGE_NAME \
      --app-insights $APPINSIGHTS_NAME \
      --app-insights-key $APPINSIGHTS_INSTRUMENTATIONKEY \
      --image $AZURE_CONTAINER_REGISTRY_ENDPOINT/$IMAGE
```

my current version posture:

```text
azure-cli                         2.48.1 *

core                              2.48.1 *
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.137
application-insights              0.1.19
containerapp                      0.3.33

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/kai/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Apr 25 2023, 04:23:10) [GCC 11.3.0]
```

**Comment by raorugan** [comment]
looking into this

**Comment by SushmithaVReddy** [comment]
Hi @KaiWalter , I'll be trying to reproduce this and get back to you.

**Comment by raorugan** [comment]
@KaiWalter  the fix is in progress! if this is high priority pls enable from AppInsights of functions resource. Once deployment completes will let you know

**Comment by kamperiadis** [comment]
Marking as closed as this should already have been resolved with my changes
