### ISSUE TITLE
Unable to connect to other apps in environment via container app name

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-functions-on-container-apps#26]
I'm unable to connect to other function apps in the same Container App Environment via the application name, such as `https://<app-name>/api/GetProducts`.

Should I be able to connect to other function apps using the approach indicated at https://learn.microsoft.com/en-us/azure/container-apps/connect-apps?

For example, I have FunctionAppA that wants to make an HTTP call to FunctionAppB.  Both FunctionAppA and FunctionAppB are apps in the same environment.

**Comment by SushmithaVReddy** [comment]
Hi @mcollier , can you share us more details? What is the error/exception you are seeing? What is the auth level used in Function app B? 

Yes, the methods mentioned in  https://learn.microsoft.com/en-us/azure/container-apps/connect-apps should work. As per your question, I see the url you are trying to hit is https://<app-name>/api/GetProducts - this method works in combination with dapr enablement. Can you share us if you are seeing any errors in dapr side car?

**Comment by mcollier** [comment]
Hello, @SushmithaVReddy!

The auth level used in Function App B is set to Anonymous.  I'm able to invoke Function App B using the FQDN such as https://mcfuncacad-products-api.xxxxxxxx.northeurope.azurecontainerapps.io/api/GetProducts. 

Attempting to make a request to https://mcfuncacad-products-api/api/GetProducts results in a TimeoutException.

I'm assuming I can use https://mcfuncacad-products-api/api/GetProducts based on the third bullet below:

![image](https://github.com/Azure/azure-functions-on-container-apps/assets/1142273/67e433eb-140d-44d5-9503-7bf7c0067870)
_source: https://learn.microsoft.com/en-us/azure/container-apps/connect-apps_ 

If I'm correctly understanding "the container app name, for instance http://<APP_NAME> for internal requests", I would not need to configure Dapr.  Is that understanding correct?

**Comment by SushmithaVReddy** [comment]
Hi @mcollier , you are right that https://mcfuncacad-products-api/api/GetProducts call should work as https://mcfuncacad-products-api.xxxxxxxx.northeurope.azurecontainerapps.io/api/GetProducts if both your Function app A and B are in same managed env. I'm checking this with container apps team on why timeouts would occur.

**Comment by SushmithaVReddy** [comment]
@mcollier please check if the Function A to B call is made using Https. Containers apps today supports only http for internal calls.

**Comment by mcollier** [comment]
@SushmithaVReddy Ok.  I think that (using HTTP instead of HTTPS) may be the fix.  I did a quick test and it seemed to work!  I'll try some more early this week and report back.  Thank you!

**Comment by mcollier** [comment]
Using HTTP seems to work. Thank you, @SushmithaVReddy!

I think it would be helpful if the Container Apps documentation made it clearer that only HTTP is supported for internal calls.  It's very easy to miss in the current documentation.

**Comment by CezaryKlus** [comment]
> I think it would be helpful if the Container Apps documentation made it clearer that only HTTP is supported for internal calls. It's very easy to miss in the current documentation.

This should be clearly stated in the documentation. I lifted-and-shifted my solution that relies on app names and calls via HTTPS e.g. https://other-app/api...
I found that internally services only expose port 80 via cluster IP?

The documentation encourages this type of calls without clearly stating the limitations

https://learn.microsoft.com/en-us/azure/container-apps/connect-apps?tabs=bash#call-a-container-app-by-name

**Comment by Voxis** [comment]
another question, i have two apps in the same azure container environment with ingress. 

if i console/shell into one of the apps, and attempted ping the-other-app, it resolved the internal ip address but cannot get a reply. is this expected?
