### ISSUE TITLE
A stamp with the specified name already exists in the location BLU

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-functions-on-container-apps#28]
When attempting to deploy a new Function app in a Container App Environment, I received an "A stamp with the specified name already exists in the location BLU" error.

I'm not sure what "BLU" is in this context.  The error doesn't give me enough information to resolve.

```json
{
  "code": "DeploymentFailed",
  "target": "/subscriptions/xxxxxx/resourceGroups/rg-func-aca-mcollier/providers/Microsoft.Resources/deployments/func-apps-deployment",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "target": "/subscriptions/xxxxxx/resourceGroups/rg-func-aca-mcollier/providers/Microsoft.Resources/deployments/func-apps-deployment",
      "message": "A stamp with the specified name already exists in the location BLU."
    }
  ]
}
```

**Comment by raorugan** [comment]
Thanks for reporting this issue. BLU here means East US region. We are investigating the root cause of this issue, this is a known intermittent issue. We are adding more logs to get the reason. Can you re-try with different name and let us know?

**Comment by mcollier** [comment]
I was able to successful provision the resources by using a new resource group name and new Container Apps Environment name.
