### ISSUE TITLE
M1 macs need special instructions 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-on-container-apps#30]
Please see this comment for workaround, without it, customers will see "Function not implemented" error: https://github.com/Azure/azure-functions-core-tools/issues/2901#issuecomment-1597911137

**Comment by raorugan** [comment]
Which workaround worked for you @lilyjma? is it adding --platform (set platform to "linux/amd64" when running docker build)

**Comment by lilyjma** [comment]
No I followed instructions here http://issamben.com/running-azure-function-as-docker-container-on-an-m1-m2/ and made the changes on Docker Desktop

**Comment by raorugan** [comment]
@lilyjma can we close this issue? Please confirm if this is resolved
