### ISSUE TITLE
Request: NodeJs Example

### ISSUE THREAD

**Issue by SamOyeAH** [Azure/azure-functions-on-container-apps#35]
My team is currently using Azure functions. 

I am curious about moving to Azure Functions on Container Apps.

Would it be possible to provide a Nodejs example for Azure Functions on Container Apps?

**Comment by raorugan** [comment]
In your local machine create the Nodejs sample by executing following command
func init LocalFunctionProj --worker-runtime node --docker 
Post this follow the link for the remaining steps - https://github.com/Azure/azure-functions-on-container-apps#create-the-local-function-project-c-isolated---http-trigger

Optionally while creating functionapp using Az CLI -  az functionapp, you may provide runtime as "node"

az functionapp create --resource-group MyResourceGroup --name <functionapp_name> \
--environment MyContainerappEnvironment \
--storage-account <Storage_name> \
--functions-version 4 \
--runtime node \
--image <DOCKER_ID>/<image_name>:<version>

**Comment by SamOyeAH** [comment]
Thank you @raorugan
