### ISSUE TITLE
Can sensitive values (i.e. connection strings, credentials, etc.) be secrets in Key Vault?

### ISSUE THREAD

**Issue by omon77** [Azure/azure-functions-on-container-apps#38]
Just looking for confirmation and examples...
The app settings are coming from Environment variables by default.
In a case of having an Azure Function (hosted in Azure Container App) having Service Bus Topic trigger, is pointing the value of environment variable for app setting name to Key Vault secret supported?

**Comment by raorugan** [comment]
this feature needs Managed identity support for which the work is in progress. Will Update once MI support is out.
