### ISSUE TITLE
Unable to assign roles or managed identity to underlying container apps

### ISSUE THREAD

**Issue by Vedantthakkar** [Azure/azure-functions-on-container-apps#43]
Hi,

We have created function apps which are deployed in container app env. Now we need to assign certain roles to the function app to access azure resources which require RBAC access. Since the identity is linked to underlying container apps and those container apps are created in a separate resource group with deny assignment, we are not able to add roles or managed identities to those container apps. 

Is there anyway we can provide RBAC access to these function apps which are deployed in container app env?

**Comment by eduards-vavere** [comment]
You can just open the container app with the same name as your function app and assign the managed identity there.

**Comment by raorugan** [comment]
hey hi again @eduards-vavere , users will not be able to modify/make changes to the underlying container app

**Comment by eduards-vavere** [comment]
Workaround, you can set these in app settings if you have a service principal

AZURE_TENANT_ID=
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=

**Comment by stishkin** [comment]
@raorugan  is there any progress on this feature ?

**Comment by raorugan** [comment]
We are targeting to release this feature system/user identity by end of April

**Comment by ryan00** [comment]
What is the latest status on this issue?

**Comment by raorugan** [comment]
Managed Identity - User/system assigned is released and now supported. Please check it out and let us know your feedback.
https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp
