### ISSUE TITLE
Add start/stop button to azure function

### ISSUE THREAD

**Issue by eduards-vavere** [Azure/azure-functions-on-container-apps#44]
Hi,

Simple request: add start/stop button to the azure function hosted as container app. Restart would also be great.

**Comment by raorugan** [comment]
Sure we are looing into this, can you please provide use-case details ?  what is restricting currently without this capability? Appreciate your inputs and it would be very helpful for us. Thank you.

**Comment by eduards-vavere** [comment]
- For troubleshooting.
- Stopping an expected runaway process quickly (ex. wrong processing, security breach).
- If that resource takes from queue X, I would like to stop it and test against that queue X from my local machine
- Switching between this new function app as a container app and the older implementation in regular function app (as safety net)

**Comment by raorugan** [comment]
This feature is now available!
