### ISSUE TITLE
Bicep template needs example how to provide private registry

### ISSUE THREAD

**Issue by eduards-vavere** [Azure/azure-functions-on-container-apps#45]
In Azure portal can create function app with private registry - works good

But how to define this in bicep?

I tried using the APP_SETTINGS fields (from other github issues), but something did not work (and no documentation). Need proper specification/example

**If it's ACR why am I using it as private registry?**

Because my app is in DEV subscription, but registry is in PROD subscription, and not possible to link it as ACR across-subscriptions

![2024-02-28 13_41_41-maintainer-tasks-dev - Microsoft Azure - Vivaldi](https://github.com/Azure/azure-functions-on-container-apps/assets/71697844/eff418b2-5f4d-4067-aa9e-df85296d6b23)

**Comment by raorugan** [comment]
Sure @eduards-vavere .. will update this and keep this posted

**Comment by eduards-vavere** [comment]
Looks like these sets of env vars seem to do the trick :)

siteConfig: {
      linuxFxVersion: 'DOCKER|myreg.azurecr.io/email-sender:pipeline-2024-02-26_11-44-13'
      appSettings: [

        {
          name: 'DOCKER_REGISTRY_SERVER_URL'
          value: 'myreg.azurecr.io'
        }
        {
          name: 'DOCKER_REGISTRY_SERVER_USERNAME'
          value: 'myreg'
        }
        {
          name: 'DOCKER_REGISTRY_SERVER_PASSWORD'
          value: containerRegistryRef.listCredentials().passwords[0].value
        }
        {
          name: 'DOCKER_CUSTOM_IMAGE_NAME'
          value: 'DOCKER|myreg.azurecr.io/email-sender:pipeline-2024-02-26_11-44-13'
        }

**Comment by raorugan** [comment]
yes registry_server, registry_username , password and image are needed apart from linuxFxVersion value

**Comment by raorugan** [comment]
the query has been addressed
