### ISSUE TITLE
Support for start/stop Azure functions hosted on Azure Containers Apps

### ISSUE THREAD

**Issue by benoitsautierecellenza** [Azure/azure-functions-on-container-apps#48]
While performing update of environment variables on Azure function hosted on Azure Container Apps Azure Activity log report :
- Stop Web App report `This is currently not supported.`
- Update web sites config report  report conflict `
Cannot modify this site because another operation is in progress.`
- UpdateWebSite reported a failed state even if operation is successfull

Is there an alternate way to perform Environment variables on Azure Function hosted on Azure Container Apps.

**Comment by raorugan** [comment]
Can you confirm which function appsettings are you planning to update?

Can you please provide use-case scenario details of start/stop? We are actively looking into this

**Comment by benoitsautierecellenza** [comment]
Hi,

I had a set of Azure functions working on consumption / premium plan that I moved to Azure Container Apps. Because I needed to start and stop my application that rely on multiple functions, I had a Github Action Workflow that organize the start/ stop of each function using Update-AzFunctionAppSetting (Az.Functions module version 4.0.7). By managing environments variables just like “AzureWebJobs.<Functio  Name>.Disabled”. This approach was working before Container Apps but not now. When performing such operation I faced to multiple errors such as one mentioned in my issue.

At the beginning, I was thinking that I needed to update Az.Functions module to latest version but I discovered those entries as illustrated bellow : 
![image](https://github.com/Azure/azure-functions-on-container-apps/assets/39596158/1555fc4d-154a-4224-90b0-929921b95c0d)

**Comment by raorugan** [comment]
May I know which trigger/binding are you using? Why do you need to start , stop these function apps?

**Comment by raorugan** [comment]
Since you have multiple queries, would like to understand your scenarios and requirements better. Please let me know if you would like to hop onto a call to discuss the same. Please drop a note to raorugan@microsoft.com

**Comment by raorugan** [comment]
Thanks for the conversation!

**Comment by raorugan** [comment]
this feature is now out , you may check it out using "az functionapp stop --name --resource-group . The portal access will be out soon as it is currently work in progress.

**Comment by benoitsautierecellenza** [comment]
Hi @raorugan. That's a fantastic news. Will be tested within three weeks.

**Comment by benoitsautierecellenza** [comment]
Hi,

Tested, fully functionnal.
