### ISSUE TITLE
Update CPU and Memory

### ISSUE THREAD

**Issue by ogix** [Azure/azure-functions-on-container-apps#49]
By default Azure functions on Container Apps creates a container with 1 CPU core and 2Gi of memory. How do I update using CLI or Azure portal?

I tried running this command:
`az functionapp config container set --cpu 0.5 --memory 1.0Gi --name {Name} --resource-group {ResourceGroup} `

But go this error:
**Resource configuration is not supported for Azure Functions on Azure Container apps with Consumption only environment type**

How do I update then?

**Comment by raorugan** [comment]
May I know which version of CLI are you using? Please update CLI to the latest version ! Please provide workload profile name as upgrading configs is supported only in workload profile - consumption or dedicated plans. Here is the example

az functionapp config container set --name <funcname> \
--workload-profile-name <wpname> \
--resource-group ,rgname> \
--cpu 0.5 \
--memory 1Gi 
Additionally you can configure using portal 
![image](https://github.com/Azure/azure-functions-on-container-apps/assets/45637559/bc27e942-0e6a-42f2-97f3-26b1c2e093c7)

**Comment by raorugan** [comment]
closing this issue since as the query is being addressed
