### ISSUE TITLE
Why did you remove option to see invocation history?

### ISSUE THREAD

**Issue by eduards-vavere** [Azure/azure-functions-on-container-apps#50]
It was very useful for our team to be able to look at it as regular function app. Please bring it back. Now I only see this message. Yes, I have app insight set up and they are working (Still this message).

![invhistory](https://github.com/Azure/azure-functions-on-container-apps/assets/71697844/7d5b4130-94db-4f96-bb59-666e852c2c0f)

**Comment by raorugan** [comment]
Hi @eduards-vavere  you should be able to configure appInsights later or during the create time. What issue are you facing here?

**Comment by eduards-vavere** [comment]
I'm talking about the invocation history! What was there before this popup!

**Comment by raorugan** [comment]
No it was not removed , here is the screenshot of a function app invocations
![image](https://github.com/Azure/azure-functions-on-container-apps/assets/45637559/62a92151-8fae-4f79-87f7-e76e0977aaee)

**Comment by eduards-vavere** [comment]
OK, thanks. I will see if somehow I can get it work.

**Comment by eduards-vavere** [comment]
I still don't see the invocation history. Only prompt to attach AI. I have app insight attached. It only offers me to change the app insight to different one.

I am using:
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: appInsightConnectionString
        }
        
And in UI it shows correctly as attached.

**Comment by raorugan** [comment]
Can you please let me know which trigger is this?

**Comment by eduards-vavere** [comment]
Checked all these triggers - Service Bus, Queue, Http and timer.  I checked all my 3 function apps - all have the warning in the picture.
![nomonitor](https://github.com/Azure/azure-functions-on-container-apps/assets/71697844/c70d8b13-2dd6-4609-913c-fe0946f5eace)

It was working before in March.

Under function app / Application Insights 
"Your app is connected to Application Insights resource: name-of-my-app-insight"

**Comment by raorugan** [comment]
Hi @eduards-vavere , there is an issue with invocations tab in the portal. The fix is being rolled out and ETA is May 20. If this is urgent, please email me - raorugan@microsoft.com , we can unblock you.

**Comment by eduards-vavere** [comment]
Thanks for info and reply! :)

**Comment by eduards-vavere** [comment]
It started to work again today. Thanks

**Comment by raorugan** [comment]
Should be stable now. Please let me know the if you are seeing any errors
