### ISSUE TITLE
Blocker bug - can not deploy, previous deployment ongoing (But not our deployment)

### ISSUE THREAD

**Issue by eduards-vavere** [Azure/azure-functions-on-container-apps#53]
**Which trigger/binding are you using?**
All of them

**Which language are you using?**
C#

**Expected behavior**
Can deploy bicep, can deploy CD using powershell

**Actual behavior**
On bicep:

previous deployment from '5/10/2024 10:38:41 AM' is still active (expiration time is '5/17/2024 10:38:40 AM')

On CD pipeline:

Deploying FUNCTION app to container app env
##[error]ERROR: Operation returned an invalid status 'Conflict'
##[error]Content: {"Code":"Conflict","Message":"Cannot modify this site because another operation is in progress. Details: Id: c5c53386-fe18-49fd-803e-efcead44c6bf, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 5/10/2024 10:45:02 AM, RequestId: e83bb5cb-2fef-4a8b-afc5-1aed39113bdd, EntityType: 3","Target":null,"Details":[{"Message":"Cannot modify this site because another operation is in progress. Details: Id: c5c53386-fe18-49fd-803e-efcead44c6bf, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 5/10/2024 10:45:02 AM, RequestId: e83bb5cb-2fef-4a8b-afc5-1aed39113bdd, EntityType: 3"},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"59203","MessageTemplate":"Cannot modify this site because another operation is in progress. Details: {0}","Parameters":["Id: c5c53386-fe18-49fd-803e-efcead44c6bf, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 5/10/2024 10:45:02 AM, RequestId: e83bb5cb-2fef-4a8b-afc5-1aed39113bdd, EntityType: 3"],"Code":"Conflict","Message":"Cannot modify this site because another operation is in progress. Details: Id: c5c53386-fe18-49fd-803e-efcead44c6bf, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 5/10/2024 10:45:02 AM, RequestId: e83bb5cb-2fef-4a8b-afc5-1aed39113bdd, EntityType: 3"}}],"Innererror":null}

**To Reproduce**
1. Bicep deploy or powershell deploy

I looked in my deployments, I do not have any ongoing, so this ongoing is hidden from me.

**Comment by eduards-vavere** [comment]
I am guessing this could be related to the invocation history fix, but just a wild guess

**Comment by eduards-vavere** [comment]
Bicep started to work. CD pipe still broken

##[error]ERROR: Operation returned an invalid status 'Conflict'
Code":"Conflict","Message":"Cannot modify this site because another operation is in progress. Details: Id: 6511d80c-f696-4fbf-81a1-745c7da6cf4c, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 5/14/2024 6:35:14 AM, RequestId: 5b96b25c-be4c-45e2-b914-6a215eca30b2, EntityType: 3"}}],"Innererror":null}

**Comment by eduards-vavere** [comment]
Even after deleting and re-creating the component I am getting this same error

**Comment by vivekjilla** [comment]
Hi @eduards-vavere, can you please share the commands you run as part of your CD. We identified one issue in az cli command and working towards a fix. Would like to check if we can provide a workaround meanwhile based on your usage.

**Comment by eduards-vavere** [comment]
@vivekjilla thanks for reply, this is still blocker issue. the command is:
 az functionapp config container set --image $fullImageName --name $applicationName --resource-group $resourceGroupName

**Comment by vivekjilla** [comment]
Thanks @eduards-vavere , can you please use this command meanwhile, by replacing the `<acr name>.azurecr.io/azure-functions/dotnet8-quickstart-demo:1.0` with your image details:
```sh
az resource update \
   -g $resourceGroupName \
   -n $applicationName/config/web \
   --resource-type 'Microsoft.Web/sites/config' \
   --set properties.linuxFxVersion="DOCKER|<acr name>.azurecr.io/azure-functions/dotnet8-quickstart-demo:1.0"
```

**Comment by eduards-vavere** [comment]
@vivekjilla IT WORKED. Thanks. Should I keep using this command in future?
