### ISSUE TITLE
azurefunctionstest.azurecr.io/azure-functions/dotnet7-quickstart-demo:1.0 tag does not exist

### ISSUE THREAD

**Issue by eduards-vavere** [Azure/azure-functions-on-container-apps#55]
In example docs mentioned to use:
azurefunctionstest.azurecr.io/azure-functions/dotnet7-quickstart-demo:1.0

But error:
Error response from daemon: manifest for azurefunctionstest.azurecr.io/azure-functions/dotnet7-quickstart-demo:1.0 not found: manifest unknown: manifest tagged by "1.0" is not found

**Comment by vivekjilla** [comment]
Hi @eduards-vavere thanks for reporting this. Please use the image `mcr.microsoft.com/azure-functions/dotnet8-quickstart-demo:1.0` instead.  Can you please let us know the example docs you're referring to. We have updated the Readme in this repo with correct reference now.

**Comment by eduards-vavere** [comment]
Works now. Thanks. Yes, it was in readme. Closing.
