### ISSUE TITLE
[Azure Monitor Application Insights] - Support for Application Insights auto-instrumentation agent

### ISSUE THREAD

**Issue by benoitsautierecellenza** [Azure/azure-functions-on-container-apps#60]
As a PowerShell developer, I write most of my Azure functions in PowerShell and rely on the Application Insights auto-instrumentation agent. while migrating my application to Azure Functions on Containers Apps, I discovered that solution does not support this useful feature

Is there a plan to support auto-instrumentation agent or do I have to instrument my code using Application Insights SDKs?

Best option would be to have native support for Application Insights auto-instrumentation agent

Alternate solution would be to develop / implement another way to collect traces from my Azure functions

Thank you.

**Comment by raorugan** [comment]
hi @benoitsautierecellenza  can you please share the steps you implemented to configure auto-instrumentation agent in functions on ACA?

**Comment by benoitsautierecellenza** [comment]
Hi,

In fact, this is not an issue with Azure Container Apps but support for OpenTelemetry in Azure Function for PowerShell : 
https://learn.microsoft.com/en-us/azure/azure-functions/opentelemetry-howto?tabs=app-insights&pivots=programming-language-powershell

![image](https://github.com/Azure/azure-functions-on-container-apps/assets/39596158/fb3093b2-a703-4f42-b298-4f08444683a8)

My Azure function is configured with an environment variable referencing my Application Insights instrumentation key

I was expecting the same behavior as Azure Function (just provide the instrumentation Key / Connection string) but it's not as simple with OpenTelemetry. I will have a look at the rest of this article.

best regards.

**Comment by benoitsautierecellenza** [comment]
Hi,

confirmed, my implementation of Application Insights is not in fault. The same container with same environment variables is fully functionnal on Azure Function consumption plan and Azure Function with Docker container. So this issue is not related to Azure Funtion on Azure Container Apps.

**Comment by raorugan** [comment]
Thanks for confirming on this @benoitsautierecellenza ! We are tracking OTEL support in func on ACA as well - https://github.com/Azure/azure-functions-on-container-apps/issues/62. Will close this issue.

**Comment by benoitsautierecellenza** [comment]
Hi, 

Finally found the root cause after some tests and discovered that it was an authentication issue with Application Insights : [OpenTelemetry data agent does not support RBAC for app insights](https://github.com/microsoft/azure-container-apps/issues/1340). Once `DisableLocalAuth` set to `true`, Application Insights Auto-instrucmentation start working.
