### ISSUE TITLE
Unable to update image from private Docker repo

### ISSUE THREAD

**Issue by peter-mskeng** [Azure/azure-functions-on-container-apps#66]
**Which trigger/binding are you using?**
Http

**Which language are you using?**
Typescript/Nodejs

**Provide resource details**
 1. Function app name: msk-functions-node
 2. Resource Id: /subscriptions/e0f035e9-2d23-4fa1-bc02-b4367ea174f1/resourceGroups/MskContainerappEnvironment_FunctionApps_88542ce8-3b01-4d55-9ced-410277f17b64/providers/Microsoft.App/containerapps/msk-functions-node

**Expected behavior**
`az functionapp config container set` works equally with public Docker repos, private Docker repos, and Azure Container Registries.

**Actual behavior**
`az functionapp config container set` succeeds with public Docker repos, private Azure Container Registries, but fails with private Docker repos.

**To Reproduce**

1. Follow tutorial here, using public Docker repo: https://learn.microsoft.com/en-us/azure/azure-functions/functions-deploy-container-apps?tabs=acr%2Cbash&pivots=programming-language-typescript
2. Make Docker repo private.
3. Update image from private Docker repo:

```
az functionapp config container set `
  --name msk-functions-node `
  --resource-group  AzureFunctionsContainers-rg `
  --image <DOCKER ID>/<IMAGE NAME> `
  --registry-server registry.hub.docker.com `
  --registry-username <DOCKER ID> `
  --registry-password <PASSWORD>
```

3. Update fails with 500 Internal Server Error:

> {"Code":"InternalServerError","Message":"Internal server error occurred. Operation failed: Internal Server Error","Target":null,"Details":[{"Message":"Internal server error occurred. Operation failed: Internal Server Error"},{"Code":"InternalServerError"},{"ErrorEntity":{"ExtendedCode":"51017","MessageTemplate":"Internal server error occurred. {0}","Parameters":["Operation failed: Internal Server Error"],"Code":"InternalServerError","Message":"Internal server error occurred. Operation failed: Internal Server Error"}}],"Innererror":null}

4. Try same command with new private Docker repo, still fails.

**Screenshots**

**Logs**
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e0f035e9-2d23-4fa1-bc02-b4367ea174f1/resourceGroups/AzureFunctionsContainers-rg/providers/Microsoft.Web/sites/msk-functions-node/config/web?api-version=2023-01-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '140'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '11cb47e0-3eec-11ef-a823-5048494f4e43'
cli.azure.cli.core.sdk.policies:     'CommandName': 'functionapp config container set'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --image --registry-server --registry-username --registry-password --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.62.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"linuxFxVersion": "DOCKER|<DOCKER ID>/<IMAGE NAME>", "functionAppScaleLimit": 10, "minimumElasticInstanceCount": 0}}
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/e0f035e9-2d23-4fa1-bc02-b4367ea174f1/resourceGroups/AzureFunctionsContainers-rg/providers/Microsoft.Web/sites/msk-functions-node/config/web?api-version=2023-01-01 HTTP/1.1" 500 542
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '542'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '200'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '3000'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '5ea0abe1-f157-433f-a009-0975c8feb5ac'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '5ea0abe1-f157-433f-a009-0975c8feb5ac'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS2:20240710T184617Z:5ea0abe1-f157-433f-a009-0975c8feb5ac'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 44F36882367F4AF58669CBA9FEA691BC Ref B: MNZ221060609039 Ref C: 2024-07-10T18:46:03Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 10 Jul 2024 18:46:17 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Code":"InternalServerError","Message":"Internal server error occurred. Operation failed: Internal Server Error","Target":null,"Details":[{"Message":"Internal server error occurred. Operation failed: Internal Server Error"},{"Code":"InternalServerError"},{"ErrorEntity":{"ExtendedCode":"51017","MessageTemplate":"Internal server error occurred. {0}","Parameters":["Operation failed: Internal Server Error"],"Code":"InternalServerError","Message":"Internal server error occurred. Operation failed: Internal Server Error"}}],"Innererror":null}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1872, in update_configuration_polling
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_appservice_utils.py", line 21, in _generic_site_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2023_01_01/operations/_web_apps_operations.py", line 21870, in update_configuration
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Internal Server Error'
Content: {"Code":"InternalServerError","Message":"Internal server error occurred. Operation failed: Internal Server Error","Target":null,"Details":[{"Message":"Internal server error occurred. Operation failed: Internal Server Error"},{"Code":"InternalServerError"},{"ErrorEntity":{"ExtendedCode":"51017","MessageTemplate":"Internal server error occurred. {0}","Parameters":["Operation failed: Internal Server Error"],"Code":"InternalServerError","Message":"Internal server error occurred. Operation failed: Internal Server Error"}}],"Innererror":null}

**Additional context**

As mentioned above, this operation succeeds with a public Docker repo, and also succeeds with a private Azure Container Registry. It only fails with a private Docker repo. I have tested the password from docker login and confirmed that it works.

**Comment by mukundnigam** [comment]
@peter-mskeng What is the image format your are giving for private docker case ? Can you try this "registry.hub.docker.com/image", eg. "registry.hub.docker.com/mukundnigam/testprivaterepo:v2"

**Comment by peter-mskeng** [comment]
The value I was giving for --image was in the format "docker-id/repo-name:tag".

I just tried "registry.hub.docker.com/docker-id/repo-name:tag":

1. first time as a private repository it failed with the same internal server error as before, extended code 51017. I was very sad, my hoped were dashed...
2. second time as a public repository it succeeded. I wanted to confirm the longform fully-qualified image name actually worked, and it did.
3. third time as a private repository it succeeded! Happily surprised, yet not surprised.

Two more surprising thing I noticed watching the --debug output and refreshing the active revisions pane in the portal while it ran:

1. One deployment from the CLI activates and deactivates numerous revisions in the portal. Naively, I would have expected it to activate a single new revision, and then deactivate a single old one. Does this help account for how long the deployment takes?
2. Many commands issued by the CLI return a 429 status code. Here is a typically example:

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e0f035e9-2d23-4fa1-bc02-b4367ea174f1/resourceGroups/AzureFunctionsContainers-rg/providers/Microsoft.Web/sites/msk-functions-node/config/web?api-version=2023-01-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '165'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '38df05f6-3f9d-11ef-8a64-5048494f4e43'
cli.azure.cli.core.sdk.policies:     'CommandName': 'functionapp config container set'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --image --registry-server --registry-username --registry-password --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.62.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"linuxFxVersion": "DOCKER|registry.hub.docker.com/<DOCKER ID>/<IMAGE>", "functionAppScaleLimit": 10, "minimumElasticInstanceCount": 0}}
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/e0f035e9-2d23-4fa1-bc02-b4367ea174f1/resourceGroups/AzureFunctionsContainers-rg/providers/Microsoft.Web/sites/msk-functions-node/config/web?api-version=2023-01-01 HTTP/1.1" 429 1265
cli.azure.cli.core.sdk.policies: Response status: 429
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1265'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Retry-After': '30'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '81706444-45ef-4092-8e93-cb16f4268e55'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '81706444-45ef-4092-8e93-cb16f4268e55'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS2:20240711T155314Z:81706444-45ef-4092-8e93-cb16f4268e55'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 19C144BE42854836BB2017D9B5E4F366 Ref B: MNZ221060608011 Ref C: 2024-07-11T15:53:13Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 11 Jul 2024 15:53:14 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Code":"Conflict","Message":"Cannot modify this site because another operation is in progress. Details: Id: 7113a8d8-a7fa-4b94-ab4e-5b535a8a7b19, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 7/11/2024 3:52:01 PM, RequestId: b8be8259-20cf-4a3c-bb0a-a4001b0fac76, EntityType: 3","Target":null,"Details":[{"Message":"Cannot modify this site because another operation is in progress. Details: Id: 7113a8d8-a7fa-4b94-ab4e-5b535a8a7b19, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 7/11/2024 3:52:01 PM, RequestId: b8be8259-20cf-4a3c-bb0a-a4001b0fac76, EntityType: 3"},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"51032","MessageTemplate":"Cannot modify this site because another operation is in progress. Details: {0}","Parameters":["Id: 7113a8d8-a7fa-4b94-ab4e-5b535a8a7b19, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 7/11/2024 3:52:01 PM, RequestId: b8be8259-20cf-4a3c-bb0a-a4001b0fac76, EntityType: 3"],"Code":"Conflict","Message":"Cannot modify this site because another operation is in progress. Details: Id: 7113a8d8-a7fa-4b94-ab4e-5b535a8a7b19, OperationName: ContainerAppUpdateAppSettings, CreatedTime: 7/11/2024 3:52:01 PM, RequestId: b8be8259-20cf-4a3c-bb0a-a4001b0fac76, EntityType: 3"}}],"Innererror":null}

**Comment by mukundnigam** [comment]
- During any back to back update calls, there is a possibility of receiving 429 sometimes, and the cli retries when that happens.
- az functionapp config container set could make multiple update calls to the service depending on what the command is trying to update. And this may also result in multiple versions being created.

**Comment by raorugan** [comment]
CLI may send several requests to the backend, potentially resulting in intermittent 429 errors. However, it will attempt to complete all submitted update requests and return success. Additionally, in this case `az functionapp config container set` CLI command could make multiple update calls to the service depending on what the command is trying to update., which can lead to the creation of multiple versions. However, no user action is required, as the functions will automatically select the latest version with all the necessary updates.

**Comment by peter-mskeng** [comment]
For the record, and for anyone else who stumbles over this, using the fully qualified image name for private docker repos does work, like so:

```
az functionapp config container set `
  --name <FUNCTION APP NAME> `
  --resource-group <RESOURCE GROUP> `
  --image registry.hub.docker.com/<DOCKER ID>/<IMAGE NAME> `
  --registry-server registry.hub.docker.com `
  --registry-username <DOCKER ID> `
  --registry-password <PASSWORD>
  ```

After the registry, username and password are set, you don't have to set them again for later invocations.

**Comment by mukundnigam** [comment]
Closing this as the investigation is complete.
