### ISSUE TITLE
Need more detail about "Function App provisioning failed"

### ISSUE THREAD

**Issue by eddison-shyi** [Azure/azure-functions-on-container-apps#70]
**Which trigger/binding are you using?**
HTTP Trigger

**Which language are you using?**
Python 3.11

**Provide resource details**
 1. Function app name: gurulab-service-docker (this failed to provision)
 2. Resource Id: c19817e9-a05b-40ab-a2a7-ab9b50c2f5ec (subscriptionId) location: japaneast
 3. DeploymentName: 9236f135-43fa-43eb-b964-446e7ac2d999
 4. CorrelationId: b5c99c97-db14-42c0-8cad-2727b5ca741c

**Expected behavior**
Deploy by bicep and get Azure Function on Container Apps ready

**Actual behavior**
We wanted to deploy Azure Function on Container Apps, and had tried to deploy via Azure Portal, Bicep, PowerShell, all returned message: "Function App provisioning failed" (that's all... we don't know what's going wrong and how to debug)

Other resources like storage account, application insights, log analytics workspace, container environment are all well-deployed(by bicep), except Function on Container Apps failed

To make sure whether can deploy normal azure functions, we also tried to deploy via bicep, and result is success.

**Screenshots**
Following is snapshot using bicep to deploy, and can only get "Function App provisioning failed" with empty error code
![image](https://github.com/user-attachments/assets/91f5be8b-c462-4eb8-bb2d-f6ad8d59a7d3)

**Comment by vivekjilla** [comment]
Hi @eddison-shyi, Thanks for reaching out. We're working to improve the error details. 

Meanwhile, thanks for providing the resource details. It seems to be failing with the following error when trying to pull the image: `unexpected status code 401 Unauthorized: {"details":"incorrect username or password"}`. 

Can you please check if the credentials provided are valid.

**Comment by eddison-shyi** [comment]
> Hi @eddison-shyi, Thanks for reaching out. We're working to improve the error details.
> 
> Meanwhile, thanks for providing the resource details. It seems to be failing with the following error when trying to pull the image: `unexpected status code 401 Unauthorized: {"details":"incorrect username or password"}`.
> 
> Can you please check if the credentials provided are valid and let us know.

Wow~Wow, big thanks~
We've found the misconfiguration. Once again, thanks a lot!! @vivekjilla
