### ISSUE TITLE
Start/Stop on underlying container app no longer works because of deny assignment

### ISSUE THREAD

**Issue by eduards-vavere** [Azure/azure-functions-on-container-apps#75]
I'm migrating function apps from elastic plan to container env. There are multiple issues I have to troubleshoot and during this time I NEED the option to START/STOP the function app. Previously this was possible at least in the underlying container app.

Without a START/STOP button work is very difficult, I have to delete entire resources, then modify bicep, or break them somehow by putting in invalid config. This is very unusable.

Please just add a start/stop button. Thanks.

**Comment by chandrod** [comment]
Hi @eduards-vavere, we are in the process of supporting START/STOP apis, we have already made the code changes, but need deployments and verifications before we make it available to customers.
Thanks for bringing up this issue.

**Comment by eduards-vavere** [comment]
@chandrod Awesome! :D

**Comment by raorugan** [comment]
Hi @eduards-vavere , this feature is now out , you may check it out using "az functionapp stop --name <funcname> --resource-group <RGName>. The portal access will be out soon as it is currently work in progress.

**Comment by raorugan** [comment]
Closing this issue as it is already being tracked here - https://github.com/Azure/azure-functions-on-container-apps/issues/48
