### ISSUE TITLE
Where is the option to deploy Azure Func  ACA using azd command? The Azure example of is is showing AppService?

### ISSUE THREAD

**Issue by uyen-luu** [Azure/azure-functions-on-container-apps#76]
Azure Developer CLI deployment option is available as introduced here
https://learn.microsoft.com/en-us/azure/azure-functions/functions-container-apps-hosting#deployment-options
The repository introduce about Azure Function on ACA, but the example for azd deployment option is showing host: appservice?
[samples/azdtemplates/azure.yaml](https://github.com/Azure/azure-functions-on-container-apps/blob/user/kjaju/durable-func-sample-fix/samples/azdtemplates/azure.yaml#L18)

**Comment by raorugan** [comment]
hi , please refer to this sample - https://github.com/Azure/azure-functions-on-container-apps/tree/main/samples/azdtemplates. Azure functions on ACA hosting for azd  should be referred as shown below :
![image](https://github.com/user-attachments/assets/e8bd334f-296f-4005-9e18-b82e942eaf82)

**Comment by raorugan** [comment]
closing this issue assuming the proposed solution worked!
