### ISSUE TITLE
Azure Function Timer trigger doesn't invoke accordingly to cron expression

### ISSUE THREAD

**Issue by kmadof** [Azure/azure-functions-on-container-apps#86]
**Which trigger/binding are you using?**
Timer trigger

**Which language are you using?**
F#, dotnet 8

**Provide resource details**
We cannot publicly expose those.

**Expected behavior**
I extec t execure function every hour for whole day

**Actual behavior**
I have Azure Function written in F# (dotnet 8) deployed to Container App Environment with function trigger as below
```
module TimerFunctions =
    [<Function("TimerFunction")>]
    let Run ([<TimerTrigger("0 0 * * * *")>] timer: TimerInfo, log: ILogger) =
        Console.WriteLine("================== Hey, I am a 'TimerFunction'. I am really lazy, so I only print to console ==================")
```
Sometimes this function is not invoked.

My function is scaled to 0, but this should not be an issue [for this trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-container-apps-hosting)
> While all triggers can be used, only the following triggers can dynamically scale (from zero instances) when running in a Container Apps environment:
> - HTTP
> - Azure Queue Storage
> - Azure Service Bus
> - Azure Event Hubs
> - Kafka
> - Timer

**Screenshots**
![Image](https://github.com/user-attachments/assets/a9d2332b-d99a-493e-abdb-58523437a41a)

**Additional context**
Here are version of packages I use:
```
	<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.18.1" OutputItemType="Analyzer" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.0" />
```

**Comment by raorugan** [comment]
Hi @kmadof , thanks for logging the issue here, post our investigation we would need more details of the resource. Can you please email the two issues you were facing? This will avoid exposing details publicly in the github repo. Please send them to - raorugan@microsoft.com or you may raise Azure Support ticket which is the recommended route for both the issue

**Comment by kmadof** [comment]
Hi @raorugan, I emailed you details regarding the resources in which we experienced those behaviors.H

**Comment by kmadof** [comment]
Time trigger works. The "issue" was sampling in Application Insights.

**Comment by krishnajaju** [comment]
Thanks for sharing the details offline and confirming here. Please reach out to us if you need further help.
