### ISSUE TITLE
Cannot modify this site because another operation is in progress. OperationName: StopContainerAppOperation

### ISSUE THREAD

**Issue by rmontroy** [Azure/azure-functions-on-container-apps#88]
**Which trigger/binding are you using?**
HTTP

**Which language are you using?**
Python 3.11

**Expected behavior**
Success in restart/delete/modify config

**Actual behavior**
`Cannot modify this site because another operation is in progress. Details: Id: 472ad74a-12b4-4686-8ac2-3132a46411d9, OperationName: StopContainerAppOperation, CreatedTime: 10/27/2024 9:27:40 PM, RequestId: 5506e854-5cac-4e18-810e-aac558bfcc5d, EntityType: 3`

**To Reproduce**

1. Stop function app in Az portal
2. Attempt to restart/delete/modify config

**Additional context**
I created this function app today, so earlier runtime versions shouldn't be an issue in this case.
Now I can't even delete it.

**Comment by chandrod** [comment]
We have pushed the mitigation for now for this issue, we will be deploying the long-term fix soon. Thanks.

**Comment by rmontroy** [comment]
Thanks! Delete succeeded.
