### ISSUE TITLE
The target-framework for .NET is provided but the generated Dockerfile always picks version 5.0

### ISSUE THREAD

**Issue by kamini-kamal** [Azure/azure-functions-on-container-apps#9]
Tested the follwoing scenarios:
1. `func init LocalFunctionProj1 --worker-runtime dotnet-isolated --docker --target-framework net7.0`
2. `func init LocalFunctionProj1 --worker-runtime dotnet-isolated --docker --target-framework net48`
3. `func init LocalFunctionProj1 --worker-runtime dotnet-isolated --docker --target-framework net6.0`
But got the below Dockerfile in all the cases. I had to manually edit the version to 7.0
<img width="864" alt="image" src="https://user-images.githubusercontent.com/103620498/235482978-e029ea33-daf0-4785-8c3d-6ed035f580e1.png">

`dotnet --list-sdks`
<img width="670" alt="image" src="https://user-images.githubusercontent.com/103620498/235483293-daa537dc-fb35-418a-9db3-44aa8840b840.png">

**Comment by raorugan** [comment]
this is fixed in the new core tools release
